#!/bin/bash
# By Romain Vimont (®om) <rom@rom1v.com>
#
# Link this file to ~/gitbashprompt and replace 'PS1' initialization in your
# ~/.bashrc by:
#    . /full/path/to/your/gitbashprompt
# or:
#    . /full/path/to/your/gitbashprompt '38;5;166'
# (for colorizing prompt, see below)
#
# See <http://blog.rom1v.com/2012/04/prompt-bash-pour-git/>

# To print all the 16 colors:
#   for i in {,'1;'}{30..37}; do printf "\e[${i}m █ \\\e[${i}m\n"; done
# To print all the 256 colors:
#   for i in {0..255}; do printf "\e[38;5;${i}m █ \\\e[38;5;${i}m\n"; done

__no_color='\001\e[0m\002'
if [ $# = 0 ]
then
  __prompt_color="$__no_color"
else
  __prompt_color="\001\e[$1m\002"
fi

__git_bash_prompt() {
    # default color
    local pcol="$__prompt_color"
    # branch color
    local col='\001\e[36m\002' # blue
    # detached HEAD color
    local dcol='\001\e[31m\002' # red

    SFI="$IFS"
    IFS=/
    local path="$1"
    local tokens=($path)
    IFS="$SFI"
    local i=0
    local count=${#tokens[@]}
    while [[ $i -lt $count ]]
    do
        token="${tokens[$i]}"
        etoken="$token"
        if [[ $i -gt 0 || "$path" == / ]]
        then
            printf /
            curpath="$curpath/"
        else
            if [[ "$token" == "~" ]]
            then
                etoken="$HOME"
            fi
    fi
    if [[ "$token" ]]
    then
        curpath="$curpath$etoken"
        printf "$token"
        cd "$etoken"
    else
        cd /
    fi
        if [[ -e .git ]]
        then
            gitinfo="$(git branch 2>/dev/null | sed -n 's/^* //p')"
            if [[ "$gitinfo" ]]
            then
                # if it starts by "("
                if [[ "${gitinfo::1}" == "(" ]]
                then
                  gitinfo="$(git describe --all 2>/dev/null ||
                      git rev-list HEAD -1 | cut -c-7)"
                  printf $col@$dcol"$gitinfo"$pcol
                else
                  printf $col@"$gitinfo"$pcol
                fi
            fi
        fi
    i=$(($i+1))
    done
}

PS1="$__prompt_color"'\u@\h:$(__git_bash_prompt "\w")\$'"$__no_color "
